_welcome:
    path:  /
    defaults: { _controller: AdminUserBundle:Default:home }

admin_med:
    resource: "@AdminMedBundle/Resources/config/routing.yml"
    prefix:   /

admin_unad:
    resource: "@AdminUnadBundle/Resources/config/routing.yml"
    prefix:   /

admin_user:
    resource: "@AdminUserBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AdminUserBundle:Security:login }
 
login_check:
    path: /login_check
 
logout:
    path: /logout