_welcome:
    path:  /
    defaults: { _controller: AppBundle:Default:home }

admin_med:
    resource: "@AdminMedBundle/Resources/config/routing.yml"
    prefix:   /

admin_unad:
    resource: "@AdminUnadBundle/Resources/config/routing.yml"
    prefix:   /

admin_user:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
