security:
    encoders:
        AppBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        user_db:
            entity: { class: AppBundle\Entity\User, property: username }

    firewalls:

        dev:
#           pattern:  ^/
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous:  ~
            security: false

        home:
            pattern: ^/home$
            anonymous: ~
            security: false

        secured_area:
            switch_user: { role: ROLE_ADMIN, parameter: _quieroser }
            pattern:    ^/
            anonymous: ~
#            http_basic:
#                realm: "Introduzca Usuario y Contraseña"
            form_login:
                login_path: /login
                check_path: /login_check
                default_target_path: /home/inicio

            logout:
                path: /logout
                target: /
            logout_on_user_change: true

    access_control:
      - { path: ^/home, roles: ROLE_USER }
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/admon, roles: [ROLE_ADMIN, ROLE_ADMON] }
      - { path: ^/doc, roles: [ROLE_DOC, ROLE_ADMIN] }
      - { path: ^/dec, roles: ROLE_DEC }
      - { path: ^/unad, roles: [ROLE_DEC, ROLE_ADMIN, ROLE_DOC, ROLE_SECA, ROLE_ADMON, ROLE_AVAL] }
      - { path: ^/aval, roles: [ROLE_DEC, ROLE_DIRZ, ROLE_ADMON] }
