parameters:
#    admin_user.example.class: Admin\UserBundle\Example

services:
#    admin_user.example:
#        class: %admin_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
