_escuela_unad:
    resource: "@AdminUnadBundle/Controller/EscuelaController.php"
    type:     annotation
    
_zona_unad:
    resource: "@AdminUnadBundle/Controller/ZonaController.php"
    type:     annotation
    
_centro_unad:
    resource: "@AdminUnadBundle/Controller/CentroController.php"
    type:     annotation        
    
_programa_unad:
    resource: "@AdminUnadBundle/Controller/ProgramaController.php"
    type:     annotation  
    
_docente_unad:
    resource: "@AdminUnadBundle/Controller/DocenteController.php"
    type:     annotation       

_curso_unad:
    resource: "@AdminUnadBundle/Controller/CursoController.php"
    type:     annotation
    
docente_coevaltutor:
    path:  /doc/coevaltutor
    defaults: { _controller: "AdminUnadBundle:Docente:coevaltutor" }
 
decano_coevallider:
    path:  /dec/coevallider
    defaults: { _controller: "AdminUnadBundle:Escuela:coevallider" }        